//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public Industry()
        {
            this.Member = new HashSet<Member>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Index { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Member> Member { get; set; }
    }
}
