//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Buy = new HashSet<Buy>();
            this.Sell = new HashSet<Sell>();
            this.Suppliers = new HashSet<Suppliers>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public int IndustryID { get; set; }
        public string Type { get; set; }
        public string PassWord { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string AreaID { get; set; }
        public string AreaName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string WebSite { get; set; }
        public string Fax { get; set; }
        public string QQ { get; set; }
        public string Levels { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public Nullable<System.DateTime> StarDate { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
    
        public virtual ICollection<Buy> Buy { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual ICollection<Sell> Sell { get; set; }
        public virtual ICollection<Suppliers> Suppliers { get; set; }
    }
}
