//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYiMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<News> News { get; set; }
        public DbSet<Buy> Buy { get; set; }
        public DbSet<Crafts> Crafts { get; set; }
        public DbSet<Industry> Industry { get; set; }
        public DbSet<Sell> Sell { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<Member> Member { get; set; }
    }
}
