//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYiMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int CraftsID { get; set; }
        public string Mode { get; set; }
        public string Service { get; set; }
        public string Remark { get; set; }
        public string AboutUs { get; set; }
        public string Honor { get; set; }
        public string Culture { get; set; }
        public string IsTop { get; set; }
    
        public virtual Crafts Crafts { get; set; }
        public virtual Member Member { get; set; }
    }
}
